### PR TITLE
views: filter_search_ajax Add case matching

### PR DESCRIPTION
**Pull request by michaelwood**
Adds new string case matching to add matching against FindThatCharity given names in the data.

Related: https://github.com/ThreeSixtyGiving/grantnav/issues/965

### CODE REVIEW

**Comment by michaelwood** [comment]
Will need to be rebased on https://github.com/ThreeSixtyGiving/grantnav/pull/1022

**Comment by michaelwood** [comment]
Had one more idea on this, so just testing that

**Comment by michaelwood** [comment]
> Had one more idea on this, so just testing that

Didn't work https://github.com/ThreeSixtyGiving/grantnav/issues/965#issuecomment-1879016170

This not changing this PR, is ready for review now

**Review by R2ZER0 — APPROVED** [review]
Is there not an actual case-insensitive filter?

I guess not, so Looks good :+1:

**Comment by michaelwood** [comment]
> Is there not an actual case-insensitive filter?
> 
> I guess not, so Looks good 👍

Yeah it's quite a bit more involved on the keyword field type, I think that's why it's been done like this in the existing bit. If we come to change this bit to support multiple alternative name matching I think this will be refactored out anyway and this way its more explicit what the matching rule is.

**Pull request merged**
