### PR TITLE
Add build number in footer

### PR DESCRIPTION
**Pull request by BibianaC**
Relates to #683 

Screen Shot 2021-05-14 at 15 01 11

### CODE REVIEW

**Comment by BibianaC** [comment]
@drkane @mariongalley I have added the build number at the bottom of the footer. Is this an appropriate location or would you prefer somewhere else?

**Comment by mariongalley** [comment]
Hi @BibianaC, I'm not sure if I've understood correctly, but I thought the plan might be to replace the generic Github link already in the footer that's linked to from the little icon. Would it make sense to include the link there? 
image

**Comment by BibianaC** [comment]
@mariongalley what I understood, I might not be correct, is that the GitHub icon would link to the GrantNav repo in GitHub. Now it is linked to the generic 360 GitHub. And that we would reinstate the build number as it was in the previous GN website. The build number was shown like the screen shot previously.

**Comment by mariongalley** [comment]
Ah yes, that makes sense. In that case at the bottom beneath the copyright warning seems reasonable to me.

**Comment by BibianaC** [comment]
thanks @mariongalley

**Review by michaelwood — APPROVED** [review]

**Pull request merged**
