### PR TITLE
Mw/district search

### PR DESCRIPTION
**Pull request by michaelwood**

### CODE REVIEW

**Comment by michaelwood** [comment]
[Add search to geographic filters](https://trello.com/c/9fxcqw7s/217-add-search-to-geographic-filters)

**Review by BibianaC — DISMISSED** [review]
I approve but it would be nice to:
- Have a screenshot of the changes added in the description of the PR.
- Add tests.

**Comment by michaelwood** [comment]
screenshot

Added some tests and screenshot ^

**Review by BibianaC — APPROVED** [review]
Thanks!

**Pull request merged**
