### PR TITLE
Search summary box

### PR DESCRIPTION
**Pull request by Lathrisk**
This code adds the search summary box to the search page. Closing #597

### CODE REVIEW

**Comment by drkane** [comment]
Added some comments on the dev version here: https://github.com/ThreeSixtyGiving/grantnav/issues/597#issuecomment-865983763

**Review by michaelwood — APPROVED** [review]
Great. Could you also bump the theme css date in the base template too.

**Comment by Lathrisk** [comment]
Draft pending discussion on the `smallest_grant` field in the search summary box.

**Comment by Lathrisk** [comment]
Closes #761 #760 #597 #627 
Potentially closes #636

**Comment by mariongalley** [comment]
> Potentially closes #636
Yeah I think so - now that the summary table separates the two I think they do have both have a place as the first tells you what the summary is of and the second guides your eye down to the actual results below the box.

**Review by kindly — APPROVED** [review]

**Pull request merged**
