### PR TITLE
Add UK NUTS1 regions

### PR DESCRIPTION
**Pull request by edugomez**
#376

### CODE REVIEW

**Comment by robredpath** [comment]
@morchickit - can I get your approval on this change? 

@stevieflow @BobHarper1 - does this satisfy #376 ?

**Comment by BobHarper1** [comment]
I've tested it and I'm happy. The facets would now reflect official government regions (["RGN/GOR"
 in the Standard codelist](https://github.com/ThreeSixtyGiving/standard/blob/master/codelists/geoCodeType.csv#L12)), rather than  NHS Regions (e.g. "East of England", "South East Coast", "South Central"), which will make more sense to the majority of users.

**Comment by morchickit** [comment]
It looks good on the development site. So I'm approving from my side.

**Comment by michaelwood** [comment]
Closing this pull request as it is now nearly 2 years behind master and needs further work in order fix issues mentioned by https://github.com/ThreeSixtyGiving/grantnav/pull/434#pullrequestreview-96561722

**Pull request closed without merging**
