### PR TITLE
Funders total amount only in pounds

### PR DESCRIPTION
**Pull request by BibianaC**
relates to #730 

Screen Shot 2021-09-16 at 16 25 58

### CODE REVIEW

**Comment by BibianaC** [comment]
@mariongalley what do you think?

**Comment by BibianaC** [comment]
[Funders copy - includes £ only](https://trello.com/c/12sJfVDC/210-funders-copy-includes-only)

**Comment by mariongalley** [comment]
@BibianaC I think we need to be a bit more explicit that not only are the amounts only reflecting £ grants (for those funders that do several currencies), but that funders who offer non-£ grants only are missing from the list, which is the main problem we're experiencing.

The question we get is "Why does the number of funders on this page not match the number of funders on the GrantNav homepage?"

Proposed copy from Katherine: "Total amounts shown are based on grants awarded in British pounds sterling (£) only. This means funders awarding grants in other currencies may not be listed."

**Comment by BibianaC** [comment]
Thanks for the explanation @mariongalley . I have changed the copy.

**Comment by mariongalley** [comment]
Sorry, bad timing, I **just** edited my comment to change the language from "may not be listed" to "are not listed". Please could you update it to say that?

**Comment by BibianaC** [comment]
@mariongalley I have updated it.

**Review by michaelwood — APPROVED** [review]

**Pull request merged**
