### PR TITLE
frontend: widgets: Allow columns to be selected

### PR DESCRIPTION
**Pull request by codemacabre**
Fixes https://github.com/ThreeSixtyGiving/grantnav/issues/996

### CODE REVIEW

**Comment by mariongalley** [comment]
@codemacabre Can't get the dev GrantNav widget to show up on our test site - might be a permissions/config thing as it's working fine in the preview

**Comment by mariongalley** [comment]
@codemacabre Had to look up where the browser console is but looks like yes :D

image

**Comment by codemacabre** [comment]
@mariongalley Thank you! It looks like it's because the dev site is running on `http` but your test site is using `https` so there's a security warning. Once this is deployed, it'll be served over `https` so this won't be an issue.

**Comment by mariongalley** [comment]
Thanks @codemacabre! Provided this change won't impact any existing live widgets, I'm happy for it to be deployed to live GrantNav.

**Review by mariongalley — APPROVED** [review]

**Review by michaelwood — APPROVED** [review]

**Pull request merged**
