### PR TITLE
import_to_elasticsearch: Add more fields to search index

### PR DESCRIPTION
**Pull request by michaelwood**
fixes: https://github.com/ThreeSixtyGiving/grantnav/issues/664

### CODE REVIEW

**Review by Lathrisk — APPROVED** [review]

**Comment by Lathrisk** [comment]
Is this going to impact performance if including these additional description fields in the index? Descriptions might be a lot more text to parse in a search.

**Comment by mariongalley** [comment]
> Is this going to impact performance if including these additional description fields in the index? Descriptions might be a lot more text to parse in a search.

Good question - we discussed it this afternoon with Michael and decided we might want to test this solution along with a few others, so we've renamed the related Trello card and decided to treat it more as an experiment than a definite fix https://trello.com/c/l7tRGci8/157-investigate-solutions-to-speed-up-datastore-queries-eg-add-indexes

**Comment by michaelwood** [comment]
> > Is this going to impact performance if including these additional description fields in the index? Descriptions might be a lot more text to parse in a search.
> 
> Good question - we discussed it this afternoon with Michael and decided we might want to test this solution along with a few others, so we've renamed the related Trello card and decided to treat it more as an experiment than a definite fix https://trello.com/c/l7tRGci8/157-investigate-solutions-to-speed-up-datastore-queries-eg-add-indexes (I think this is related, could be completely wrong though!)

@mariongalley  Ah this is actually a different index, the one in that trello ticket is talking about the datastore, this one is about grantnav fields in elasticsearch's index.

**Comment by michaelwood** [comment]
[Classifications field not included in search results](https://trello.com/c/vDTrwWMN/164-classifications-field-not-included-in-search-results)

**Comment by michaelwood** [comment]
Linking the issue -> https://github.com/ThreeSixtyGiving/grantnav/issues/664

**Pull request merged**
